-- NextXR Digital Twin — relational schema (SQLite 3)
--
-- GENERATED by docs/build_sql.py from nextxr-ontology/db/schema.py.
-- Do not edit by hand: add the column in db/schema.py and re-run, or the two
-- will disagree and nothing will tell you.
--
-- Scope: this is the RECORD half of the platform. The twin's graph — entities,
-- relationships and findings — lives in Neo4j and is not expressible here; see
-- docs/ER-DIAGRAM.md section 5 for that model and section 1 for why the two are
-- deliberately not joined at the database layer.
--
-- NO FOREIGN KEYS ARE DECLARED, in this file or in the running databases. That
-- is the existing design, not an omission of the generator: referential
-- integrity is enforced in the service layer (work/service.py,
-- identity/service.py) and supported by the indexes below. Adding constraints
-- here would describe guarantees the system does not actually make.
--
-- This is not a migration. It creates the schema from empty; use
-- `python -m db.migrations` to move an existing database forward.
--
-- Target: SQLite (local development). Each store is its own file under
-- nextxr-ontology/data/, so cross-store statements are not possible there.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = OFF;   -- none are declared; stated so the reader knows



-- ======================================================================
-- Migration ledger
-- ======================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_id TEXT    NOT NULL PRIMARY KEY,
    applied_at   TEXT    NOT NULL,
    duration_ms  INTEGER NOT NULL DEFAULT 0,
    checksum     TEXT    NOT NULL DEFAULT ''
);


-- ======================================================================
-- store: identity — Accounts, membership, sessions, API keys, audit
-- ======================================================================

CREATE TABLE IF NOT EXISTS organizations (
               org_id        TEXT PRIMARY KEY,
               name          TEXT NOT NULL,
               plan          TEXT NOT NULL DEFAULT 'trial',
               status        TEXT NOT NULL DEFAULT 'active',
               tenant_prefix TEXT NOT NULL,
               settings      TEXT,
               created_at    TEXT NOT NULL,
               updated_at    TEXT NOT NULL
           );

CREATE TABLE IF NOT EXISTS users (
               user_id           TEXT PRIMARY KEY,
               email             TEXT NOT NULL,
               password_hash     TEXT NOT NULL,
               name              TEXT NOT NULL DEFAULT '',
               status            TEXT NOT NULL DEFAULT 'active',
               is_platform_admin INTEGER NOT NULL DEFAULT 0,
               email_verified_at TEXT,
               created_at        TEXT NOT NULL,
               updated_at        TEXT NOT NULL,
               last_login_at     TEXT,
               failed_logins     INTEGER NOT NULL DEFAULT 0,
               locked_until      TEXT,
               mfa_secret        TEXT
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);

CREATE TABLE IF NOT EXISTS memberships (
               org_id     TEXT NOT NULL,
               user_id    TEXT NOT NULL,
               role       TEXT NOT NULL DEFAULT 'read',
               persona    TEXT NOT NULL DEFAULT 'frontline',
               created_at TEXT NOT NULL,
               PRIMARY KEY (org_id, user_id)
           );

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships (user_id);

CREATE TABLE IF NOT EXISTS sessions (
               session_id   TEXT PRIMARY KEY,
               user_id      TEXT NOT NULL,
               org_id       TEXT,
               refresh_hash TEXT NOT NULL,
               issued_at    TEXT NOT NULL,
               expires_at   TEXT NOT NULL,
               revoked_at   TEXT,
               rotated_from TEXT,
               ip           TEXT,
               user_agent   TEXT
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_refresh ON sessions (refresh_hash);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id);

CREATE TABLE IF NOT EXISTS api_keys (
               key_id       TEXT PRIMARY KEY,
               org_id       TEXT NOT NULL,
               key_hash     TEXT NOT NULL,
               prefix       TEXT NOT NULL,
               name         TEXT NOT NULL DEFAULT '',
               role         TEXT NOT NULL DEFAULT 'read',
               tenants      TEXT,
               created_by   TEXT NOT NULL DEFAULT '',
               created_at   TEXT NOT NULL,
               expires_at   TEXT,
               revoked_at   TEXT,
               last_used_at TEXT
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys (key_hash);

CREATE INDEX IF NOT EXISTS idx_api_keys_org ON api_keys (org_id);

CREATE TABLE IF NOT EXISTS org_tenants (
               tenant_id  TEXT PRIMARY KEY,
               org_id     TEXT NOT NULL,
               created_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_org_tenants_org ON org_tenants (org_id);

CREATE TABLE IF NOT EXISTS auth_tokens (
               token_hash TEXT PRIMARY KEY,
               user_id    TEXT NOT NULL,
               purpose    TEXT NOT NULL,
               created_at TEXT NOT NULL,
               expires_at TEXT NOT NULL,
               used_at    TEXT
           );

CREATE INDEX IF NOT EXISTS idx_auth_tokens_user ON auth_tokens (user_id, purpose);

CREATE TABLE IF NOT EXISTS audit_log (
               audit_id     INTEGER PRIMARY KEY AUTOINCREMENT,
               ts           TEXT NOT NULL,
               org_id       TEXT,
               actor_user   TEXT,
               actor_key    TEXT,
               action       TEXT NOT NULL,
               target_type  TEXT NOT NULL DEFAULT '',
               target_id    TEXT NOT NULL DEFAULT '',
               outcome      TEXT NOT NULL DEFAULT 'ok',
               ip           TEXT,
               user_agent   TEXT,
               detail       TEXT
           );

CREATE INDEX IF NOT EXISTS idx_audit_org ON audit_log (org_id, ts DESC);

CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log (actor_user, ts DESC);

CREATE TABLE IF NOT EXISTS hub_identities (
               hub_sub      TEXT PRIMARY KEY,
               user_id      TEXT NOT NULL,
               hub_iss      TEXT NOT NULL DEFAULT '',
               linked_at    TEXT NOT NULL,
               last_seen_at TEXT,
               linked_by    TEXT NOT NULL DEFAULT ''
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_hub_identities_user ON hub_identities (user_id);

CREATE TABLE IF NOT EXISTS hub_sso_jti (
               jti        TEXT PRIMARY KEY,
               seen_at    TEXT NOT NULL,
               expires_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_hub_sso_jti_expires ON hub_sso_jti (expires_at);



-- ======================================================================
-- store: twins — The twin registry
-- ======================================================================

CREATE TABLE IF NOT EXISTS twins (
               tenant_id     TEXT PRIMARY KEY,
               name          TEXT NOT NULL,
               domain        TEXT NOT NULL,
               description   TEXT NOT NULL DEFAULT '',
               created_at    TEXT NOT NULL,
               seed_asset_id TEXT,
               org_id        TEXT
           );

CREATE INDEX IF NOT EXISTS idx_twins_created ON twins (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_twins_org ON twins (org_id);



-- ======================================================================
-- store: work — Dispatch: teams, tasks, XP, graded runs
-- ======================================================================

CREATE TABLE IF NOT EXISTS teams (
               team_id       TEXT PRIMARY KEY,
               org_id        TEXT NOT NULL,
               name          TEXT NOT NULL DEFAULT '',
               site          TEXT NOT NULL DEFAULT '',
               shift         TEXT NOT NULL DEFAULT 'A',
               supervisor_id TEXT,
               created_at    TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_teams_org ON teams (org_id);

CREATE INDEX IF NOT EXISTS idx_teams_supervisor ON teams (supervisor_id);

CREATE TABLE IF NOT EXISTS team_members (
               team_id    TEXT NOT NULL,
               user_id    TEXT NOT NULL,
               org_id     TEXT NOT NULL,
               created_at TEXT NOT NULL,
               PRIMARY KEY (team_id, user_id)
           );

CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members (user_id);

CREATE TABLE IF NOT EXISTS tasks (
               task_id         TEXT PRIMARY KEY,
               org_id          TEXT NOT NULL,
               tenant_id       TEXT NOT NULL,
               code            TEXT NOT NULL DEFAULT '',
               title           TEXT NOT NULL,
               detail          TEXT NOT NULL DEFAULT '',
               finding_node_id TEXT NOT NULL DEFAULT '',
               asset_node_id   TEXT NOT NULL DEFAULT '',
               asset_name      TEXT NOT NULL DEFAULT '',
               behavior_id     TEXT NOT NULL DEFAULT '',
               severity        TEXT NOT NULL DEFAULT 'warning',
               scenario_id     TEXT NOT NULL DEFAULT '',
               status          TEXT NOT NULL DEFAULT 'open',
               priority        TEXT NOT NULL DEFAULT 'normal',
               assignee_id     TEXT,
               assigned_by     TEXT,
               team_id         TEXT,
               source          TEXT NOT NULL DEFAULT 'twin_finding',
               score           REAL,
               xp_awarded      INTEGER NOT NULL DEFAULT 0,
               resolution      TEXT NOT NULL DEFAULT '',
               changelog_ref   TEXT NOT NULL DEFAULT '',
               created_at      TEXT NOT NULL,
               assigned_at     TEXT,
               started_at      TEXT,
               completed_at    TEXT
           );

CREATE INDEX IF NOT EXISTS idx_tasks_org_status ON tasks (org_id, status);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee_id, status);

CREATE INDEX IF NOT EXISTS idx_tasks_finding ON tasks (finding_node_id);

CREATE INDEX IF NOT EXISTS idx_tasks_tenant ON tasks (tenant_id);

CREATE TABLE IF NOT EXISTS task_events (
               event_id   TEXT PRIMARY KEY,
               task_id    TEXT NOT NULL,
               org_id     TEXT NOT NULL,
               kind       TEXT NOT NULL DEFAULT '',
               actor_id   TEXT NOT NULL DEFAULT '',
               actor_name TEXT NOT NULL DEFAULT '',
               summary    TEXT NOT NULL DEFAULT '',
               payload    TEXT,
               created_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_task_events_task ON task_events (task_id);

CREATE TABLE IF NOT EXISTS xp_ledger (
               entry_id   TEXT PRIMARY KEY,
               org_id     TEXT NOT NULL,
               user_id    TEXT NOT NULL,
               task_id    TEXT NOT NULL DEFAULT '',
               reason     TEXT NOT NULL DEFAULT '',
               points     INTEGER NOT NULL DEFAULT 0,
               detail     TEXT NOT NULL DEFAULT '',
               created_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_xp_user ON xp_ledger (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_xp_task_reason ON xp_ledger (user_id, task_id, reason);

CREATE TABLE IF NOT EXISTS work_rules (
               rule_id       TEXT PRIMARY KEY,
               org_id        TEXT NOT NULL,
               tenant_id     TEXT NOT NULL DEFAULT '',
               behavior_glob TEXT NOT NULL DEFAULT '*',
               min_severity  TEXT NOT NULL DEFAULT 'critical',
               priority      TEXT NOT NULL DEFAULT 'high',
               scenario_id   TEXT NOT NULL DEFAULT '',
               enabled       INTEGER NOT NULL DEFAULT 1,
               seq           INTEGER NOT NULL DEFAULT 0,
               created_at    TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_work_rules_org ON work_rules (org_id, seq);

CREATE TABLE IF NOT EXISTS scenario_runs (
               run_id       TEXT PRIMARY KEY,
               org_id       TEXT NOT NULL,
               user_id      TEXT NOT NULL,
               task_id      TEXT NOT NULL DEFAULT '',
               scenario_id  TEXT NOT NULL DEFAULT '',
               mode         TEXT NOT NULL DEFAULT 'guided',
               status       TEXT NOT NULL DEFAULT 'in_progress',
               step         INTEGER NOT NULL DEFAULT 0,
               total_steps  INTEGER NOT NULL DEFAULT 0,
               score        REAL,
               passed       INTEGER NOT NULL DEFAULT 0,
               hints_used   INTEGER NOT NULL DEFAULT 0,
               wrong_steps  INTEGER NOT NULL DEFAULT 0,
               transcript   TEXT,
               started_at   TEXT NOT NULL,
               completed_at TEXT
           );

CREATE INDEX IF NOT EXISTS idx_runs_user ON scenario_runs (user_id);

CREATE INDEX IF NOT EXISTS idx_runs_task ON scenario_runs (task_id);



-- ======================================================================
-- store: changelog — Tamper-evident change log (hash-chained)
-- ======================================================================

CREATE TABLE IF NOT EXISTS events (
               seq             INTEGER PRIMARY KEY AUTOINCREMENT,
               event_id        TEXT NOT NULL UNIQUE,
               tenant_id       TEXT NOT NULL,
               entity_id       TEXT NOT NULL,
               entity_type     TEXT NOT NULL,
               actor           TEXT NOT NULL,
               action          TEXT NOT NULL,
               field_changes   TEXT NOT NULL,
               ts              TEXT NOT NULL,
               prev_event_hash TEXT NOT NULL,
               wm_hash         TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_events_tenant ON events (tenant_id, seq);

CREATE INDEX IF NOT EXISTS idx_events_entity ON events (tenant_id, entity_id, seq);



-- ======================================================================
-- store: connectors — Protocol adapters
-- ======================================================================

CREATE TABLE IF NOT EXISTS connectors (
               connector_id TEXT PRIMARY KEY,
               tenant_id    TEXT NOT NULL,
               protocol     TEXT NOT NULL,
               name         TEXT NOT NULL DEFAULT '',
               enabled      INTEGER NOT NULL DEFAULT 1,
               config       TEXT NOT NULL,
               created_at   TEXT NOT NULL,
               updated_at   TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_connectors_tenant ON connectors (tenant_id, enabled);



-- ======================================================================
-- store: devices — Ingest device credentials
-- ======================================================================

CREATE TABLE IF NOT EXISTS ingest_devices (
               device_id     TEXT PRIMARY KEY,
               tenant_id     TEXT NOT NULL,
               name          TEXT NOT NULL DEFAULT '',
               token_hash    TEXT NOT NULL,
               asset_prefix  TEXT NOT NULL DEFAULT '',
               enabled       INTEGER NOT NULL DEFAULT 1,
               created_at    TEXT NOT NULL,
               created_by    TEXT NOT NULL DEFAULT '',
               expires_at    TEXT,
               last_seen_at  TEXT,
               last_seen_ip  TEXT,
               samples_total REAL NOT NULL DEFAULT 0,
               rejected_total REAL NOT NULL DEFAULT 0
           );

CREATE INDEX IF NOT EXISTS idx_devices_tenant ON ingest_devices (tenant_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_token ON ingest_devices (token_hash);



-- ======================================================================
-- store: scenes — Cached 3-D scene payloads
-- ======================================================================

CREATE TABLE IF NOT EXISTS scene_cache (
               tenant_id   TEXT PRIMARY KEY,
               scene       TEXT NOT NULL,
               updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
           );



-- ======================================================================
-- store: bundles — Published agent bundles
-- ======================================================================

CREATE TABLE IF NOT EXISTS published_bundles (
               bundle_id   TEXT PRIMARY KEY,
               name        TEXT NOT NULL,
               domains     TEXT NOT NULL,
               payload     TEXT NOT NULL,
               tenant_id   TEXT,
               created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
           );



-- ======================================================================
-- store: threed — Photo-to-3-D job records
-- ======================================================================

CREATE TABLE IF NOT EXISTS threed_jobs (
               job_id    TEXT PRIMARY KEY,
               status    TEXT NOT NULL,
               stage     TEXT,
               filename  TEXT,
               fields    TEXT,
               stages    TEXT,
               state     TEXT,
               error     TEXT,
               created   REAL NOT NULL,
               updated   REAL NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_threed_updated ON threed_jobs (updated DESC);



-- ======================================================================
-- store: checkpoints — Agent run checkpoints
-- ======================================================================

CREATE TABLE IF NOT EXISTS checkpoints (
               thread_id   TEXT PRIMARY KEY,
               graph_name  TEXT NOT NULL,
               state       TEXT NOT NULL,
               resume_at   TEXT,
               updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
           );



-- ======================================================================
-- store: historian — telemetry measurements
--
-- Declared outside db/schema.py (see historian/schema.py): its key columns
-- need an explicit CHARACTER SET and its timestamps need microsecond
-- precision, neither of which the shared type map expresses.
-- ======================================================================

CREATE TABLE IF NOT EXISTS measurements (
    tenant_id   TEXT    NOT NULL,
    asset_id    TEXT    NOT NULL,
    signal      TEXT    NOT NULL,
    ts          TEXT    NOT NULL,
    value       REAL,
    unit        TEXT    NOT NULL DEFAULT '',
    quality     INTEGER NOT NULL DEFAULT 192,
    source      TEXT    NOT NULL DEFAULT 'api',
    received_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    PRIMARY KEY (tenant_id, asset_id, signal, ts)
);

CREATE INDEX IF NOT EXISTS measurements_tenant_signal_ts ON measurements (tenant_id, signal, ts DESC);
