-- NextXR Digital Twin — relational schema (MySQL 8)
--
-- GENERATED by docs/build_sql.py from nextxr-ontology/db/schema.py.
-- Do not edit by hand: add the column in db/schema.py and re-run, or the two
-- will disagree and nothing will tell you.
--
-- Scope: this is the RECORD half of the platform. The twin's graph — entities,
-- relationships and findings — lives in Neo4j and is not expressible here; see
-- docs/ER-DIAGRAM.md section 5 for that model and section 1 for why the two are
-- deliberately not joined at the database layer.
--
-- NO FOREIGN KEYS ARE DECLARED, in this file or in the running databases. That
-- is the existing design, not an omission of the generator: referential
-- integrity is enforced in the service layer (work/service.py,
-- identity/service.py) and supported by the indexes below. Adding constraints
-- here would describe guarantees the system does not actually make.
--
-- This is not a migration. It creates the schema from empty; use
-- `python -m db.migrations` to move an existing database forward.
--
-- Target: MySQL 8 (RDS in production). One database holds every store, so a
-- login and the twin it authorises share a transaction domain.

-- Recommended session settings for applying this file.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- CREATE DATABASE IF NOT EXISTS nextxr
--   CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
-- USE nextxr;



-- ======================================================================
-- Migration ledger
-- ======================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_id VARCHAR(255) NOT NULL PRIMARY KEY,
    applied_at   DATETIME     NOT NULL,
    duration_ms  INT          NOT NULL DEFAULT 0,
    checksum     VARCHAR(255) NOT NULL DEFAULT ''
);


-- ======================================================================
-- store: identity — Accounts, membership, sessions, API keys, audit
-- ======================================================================

CREATE TABLE IF NOT EXISTS organizations (
               org_id        VARCHAR(255) PRIMARY KEY,
               name          TEXT NOT NULL,
               plan          VARCHAR(1024) NOT NULL DEFAULT 'trial',
               status        VARCHAR(1024) NOT NULL DEFAULT 'active',
               tenant_prefix TEXT NOT NULL,
               settings      JSON,
               created_at    TEXT NOT NULL,
               updated_at    TEXT NOT NULL
           );

CREATE TABLE IF NOT EXISTS users (
               user_id           VARCHAR(255) PRIMARY KEY,
               email             VARCHAR(255) NOT NULL,
               password_hash     TEXT NOT NULL,
               name              VARCHAR(1024) NOT NULL DEFAULT '',
               status            VARCHAR(1024) NOT NULL DEFAULT 'active',
               is_platform_admin INTEGER NOT NULL DEFAULT 0,
               email_verified_at TEXT,
               created_at        TEXT NOT NULL,
               updated_at        TEXT NOT NULL,
               last_login_at     TEXT,
               failed_logins     INTEGER NOT NULL DEFAULT 0,
               locked_until      TEXT,
               mfa_secret        TEXT
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);

CREATE TABLE IF NOT EXISTS memberships (
               org_id     VARCHAR(255) NOT NULL,
               user_id    VARCHAR(255) NOT NULL,
               role       VARCHAR(1024) NOT NULL DEFAULT 'read',
               persona    VARCHAR(1024) NOT NULL DEFAULT 'frontline',
               created_at TEXT NOT NULL,
               PRIMARY KEY (org_id, user_id)
           );

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships (user_id);

CREATE TABLE IF NOT EXISTS sessions (
               session_id   VARCHAR(255) PRIMARY KEY,
               user_id      VARCHAR(255) NOT NULL,
               org_id       TEXT,
               refresh_hash VARCHAR(255) NOT NULL,
               issued_at    TEXT NOT NULL,
               expires_at   TEXT NOT NULL,
               revoked_at   TEXT,
               rotated_from TEXT,
               ip           TEXT,
               user_agent   TEXT
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_refresh ON sessions (refresh_hash);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id);

CREATE TABLE IF NOT EXISTS api_keys (
               key_id       VARCHAR(255) PRIMARY KEY,
               org_id       VARCHAR(255) NOT NULL,
               key_hash     VARCHAR(255) NOT NULL,
               prefix       TEXT NOT NULL,
               name         VARCHAR(1024) NOT NULL DEFAULT '',
               role         VARCHAR(1024) NOT NULL DEFAULT 'read',
               tenants      JSON,
               created_by   VARCHAR(1024) NOT NULL DEFAULT '',
               created_at   TEXT NOT NULL,
               expires_at   TEXT,
               revoked_at   TEXT,
               last_used_at TEXT
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys (key_hash);

CREATE INDEX IF NOT EXISTS idx_api_keys_org ON api_keys (org_id);

CREATE TABLE IF NOT EXISTS org_tenants (
               tenant_id  VARCHAR(255) PRIMARY KEY,
               org_id     VARCHAR(255) NOT NULL,
               created_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_org_tenants_org ON org_tenants (org_id);

CREATE TABLE IF NOT EXISTS auth_tokens (
               token_hash VARCHAR(255) PRIMARY KEY,
               user_id    VARCHAR(255) NOT NULL,
               purpose    VARCHAR(255) NOT NULL,
               created_at TEXT NOT NULL,
               expires_at TEXT NOT NULL,
               used_at    TEXT
           );

CREATE INDEX IF NOT EXISTS idx_auth_tokens_user ON auth_tokens (user_id, purpose);

CREATE TABLE IF NOT EXISTS audit_log (
               audit_id     BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
               ts           VARCHAR(255) NOT NULL,
               org_id       VARCHAR(255),
               actor_user   VARCHAR(255),
               actor_key    TEXT,
               action       TEXT NOT NULL,
               target_type  VARCHAR(1024) NOT NULL DEFAULT '',
               target_id    VARCHAR(1024) NOT NULL DEFAULT '',
               outcome      VARCHAR(1024) NOT NULL DEFAULT 'ok',
               ip           TEXT,
               user_agent   TEXT,
               detail       JSON
           );

CREATE INDEX IF NOT EXISTS idx_audit_org ON audit_log (org_id, ts DESC);

CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log (actor_user, ts DESC);

CREATE TABLE IF NOT EXISTS hub_identities (
               hub_sub      VARCHAR(255) PRIMARY KEY,
               user_id      VARCHAR(255) NOT NULL,
               hub_iss      VARCHAR(1024) NOT NULL DEFAULT '',
               linked_at    TEXT NOT NULL,
               last_seen_at TEXT,
               linked_by    VARCHAR(1024) NOT NULL DEFAULT ''
           );

CREATE UNIQUE INDEX IF NOT EXISTS idx_hub_identities_user ON hub_identities (user_id);

CREATE TABLE IF NOT EXISTS hub_sso_jti (
               jti        VARCHAR(255) PRIMARY KEY,
               seen_at    TEXT NOT NULL,
               expires_at VARCHAR(255) NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_hub_sso_jti_expires ON hub_sso_jti (expires_at);



-- ======================================================================
-- store: twins — The twin registry
-- ======================================================================

CREATE TABLE IF NOT EXISTS twins (
               tenant_id     VARCHAR(255) PRIMARY KEY,
               name          TEXT NOT NULL,
               domain        TEXT NOT NULL,
               description   VARCHAR(1024) NOT NULL DEFAULT '',
               created_at    VARCHAR(255) NOT NULL,
               seed_asset_id TEXT,
               org_id        VARCHAR(255)
           );

CREATE INDEX IF NOT EXISTS idx_twins_created ON twins (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_twins_org ON twins (org_id);



-- ======================================================================
-- store: work — Dispatch: teams, tasks, XP, graded runs
-- ======================================================================

CREATE TABLE IF NOT EXISTS teams (
               team_id       VARCHAR(255) PRIMARY KEY,
               org_id        VARCHAR(255) NOT NULL,
               name          VARCHAR(1024) NOT NULL DEFAULT '',
               site          VARCHAR(1024) NOT NULL DEFAULT '',
               shift         VARCHAR(1024) NOT NULL DEFAULT 'A',
               supervisor_id VARCHAR(255),
               created_at    TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_teams_org ON teams (org_id);

CREATE INDEX IF NOT EXISTS idx_teams_supervisor ON teams (supervisor_id);

CREATE TABLE IF NOT EXISTS team_members (
               team_id    VARCHAR(255) NOT NULL,
               user_id    VARCHAR(255) NOT NULL,
               org_id     VARCHAR(255) NOT NULL,
               created_at TEXT NOT NULL,
               PRIMARY KEY (team_id, user_id)
           );

CREATE INDEX IF NOT EXISTS idx_team_members_user ON team_members (user_id);

CREATE TABLE IF NOT EXISTS tasks (
               task_id         VARCHAR(255) PRIMARY KEY,
               org_id          VARCHAR(255) NOT NULL,
               tenant_id       VARCHAR(255) NOT NULL,
               code            VARCHAR(1024) NOT NULL DEFAULT '',
               title           TEXT NOT NULL,
               detail          TEXT NOT NULL DEFAULT '',
               finding_node_id VARCHAR(255) NOT NULL DEFAULT '',
               asset_node_id   VARCHAR(255) NOT NULL DEFAULT '',
               asset_name      VARCHAR(1024) NOT NULL DEFAULT '',
               behavior_id     VARCHAR(1024) NOT NULL DEFAULT '',
               severity        VARCHAR(1024) NOT NULL DEFAULT 'warning',
               scenario_id     VARCHAR(1024) NOT NULL DEFAULT '',
               status          VARCHAR(64) NOT NULL DEFAULT 'open',
               priority        VARCHAR(1024) NOT NULL DEFAULT 'normal',
               assignee_id     VARCHAR(255),
               assigned_by     VARCHAR(255),
               team_id         VARCHAR(255),
               source          VARCHAR(1024) NOT NULL DEFAULT 'twin_finding',
               score           DOUBLE,
               xp_awarded      INTEGER NOT NULL DEFAULT 0,
               resolution      TEXT NOT NULL DEFAULT '',
               changelog_ref   VARCHAR(1024) NOT NULL DEFAULT '',
               created_at      TEXT NOT NULL,
               assigned_at     TEXT,
               started_at      TEXT,
               completed_at    TEXT
           );

CREATE INDEX IF NOT EXISTS idx_tasks_org_status ON tasks (org_id, status);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee_id, status);

CREATE INDEX IF NOT EXISTS idx_tasks_finding ON tasks (finding_node_id);

CREATE INDEX IF NOT EXISTS idx_tasks_tenant ON tasks (tenant_id);

CREATE TABLE IF NOT EXISTS task_events (
               event_id   VARCHAR(255) PRIMARY KEY,
               task_id    VARCHAR(255) NOT NULL,
               org_id     VARCHAR(255) NOT NULL,
               kind       VARCHAR(1024) NOT NULL DEFAULT '',
               actor_id   VARCHAR(255) NOT NULL DEFAULT '',
               actor_name VARCHAR(1024) NOT NULL DEFAULT '',
               summary    TEXT NOT NULL DEFAULT '',
               payload    JSON,
               created_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_task_events_task ON task_events (task_id);

CREATE TABLE IF NOT EXISTS xp_ledger (
               entry_id   VARCHAR(255) PRIMARY KEY,
               org_id     VARCHAR(255) NOT NULL,
               user_id    VARCHAR(255) NOT NULL,
               task_id    VARCHAR(255) NOT NULL DEFAULT '',
               reason     VARCHAR(64) NOT NULL DEFAULT '',
               points     INTEGER NOT NULL DEFAULT 0,
               detail     TEXT NOT NULL DEFAULT '',
               created_at TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_xp_user ON xp_ledger (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_xp_task_reason ON xp_ledger (user_id, task_id, reason);

CREATE TABLE IF NOT EXISTS work_rules (
               rule_id       VARCHAR(255) PRIMARY KEY,
               org_id        VARCHAR(255) NOT NULL,
               tenant_id     VARCHAR(1024) NOT NULL DEFAULT '',
               behavior_glob VARCHAR(1024) NOT NULL DEFAULT '*',
               min_severity  VARCHAR(1024) NOT NULL DEFAULT 'critical',
               priority      VARCHAR(1024) NOT NULL DEFAULT 'high',
               scenario_id   VARCHAR(1024) NOT NULL DEFAULT '',
               enabled       INTEGER NOT NULL DEFAULT 1,
               seq           INTEGER NOT NULL DEFAULT 0,
               created_at    TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_work_rules_org ON work_rules (org_id, seq);

CREATE TABLE IF NOT EXISTS scenario_runs (
               run_id       VARCHAR(255) PRIMARY KEY,
               org_id       VARCHAR(255) NOT NULL,
               user_id      VARCHAR(255) NOT NULL,
               task_id      VARCHAR(255) NOT NULL DEFAULT '',
               scenario_id  VARCHAR(1024) NOT NULL DEFAULT '',
               mode         VARCHAR(1024) NOT NULL DEFAULT 'guided',
               status       VARCHAR(1024) NOT NULL DEFAULT 'in_progress',
               step         INTEGER NOT NULL DEFAULT 0,
               total_steps  INTEGER NOT NULL DEFAULT 0,
               score        DOUBLE,
               passed       INTEGER NOT NULL DEFAULT 0,
               hints_used   INTEGER NOT NULL DEFAULT 0,
               wrong_steps  INTEGER NOT NULL DEFAULT 0,
               transcript   JSON,
               started_at   TEXT NOT NULL,
               completed_at TEXT
           );

CREATE INDEX IF NOT EXISTS idx_runs_user ON scenario_runs (user_id);

CREATE INDEX IF NOT EXISTS idx_runs_task ON scenario_runs (task_id);



-- ======================================================================
-- store: changelog — Tamper-evident change log (hash-chained)
-- ======================================================================

CREATE TABLE IF NOT EXISTS events (
               seq             BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
               event_id        VARCHAR(255) NOT NULL UNIQUE,
               tenant_id       VARCHAR(255) NOT NULL,
               entity_id       VARCHAR(255) NOT NULL,
               entity_type     TEXT NOT NULL,
               actor           TEXT NOT NULL,
               action          TEXT NOT NULL,
               field_changes   JSON NOT NULL,
               ts              TEXT NOT NULL,
               prev_event_hash TEXT NOT NULL,
               wm_hash         TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_events_tenant ON events (tenant_id, seq);

CREATE INDEX IF NOT EXISTS idx_events_entity ON events (tenant_id, entity_id, seq);



-- ======================================================================
-- store: connectors — Protocol adapters
-- ======================================================================

CREATE TABLE IF NOT EXISTS connectors (
               connector_id VARCHAR(255) PRIMARY KEY,
               tenant_id    VARCHAR(255) NOT NULL,
               protocol     TEXT NOT NULL,
               name         VARCHAR(1024) NOT NULL DEFAULT '',
               enabled      INTEGER NOT NULL DEFAULT 1,
               config       JSON NOT NULL,
               created_at   TEXT NOT NULL,
               updated_at   TEXT NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_connectors_tenant ON connectors (tenant_id, enabled);



-- ======================================================================
-- store: devices — Ingest device credentials
-- ======================================================================

CREATE TABLE IF NOT EXISTS ingest_devices (
               device_id     VARCHAR(255) PRIMARY KEY,
               tenant_id     VARCHAR(255) NOT NULL,
               name          VARCHAR(1024) NOT NULL DEFAULT '',
               token_hash    VARCHAR(255) NOT NULL,
               asset_prefix  VARCHAR(1024) NOT NULL DEFAULT '',
               enabled       INTEGER NOT NULL DEFAULT 1,
               created_at    TEXT NOT NULL,
               created_by    VARCHAR(1024) NOT NULL DEFAULT '',
               expires_at    TEXT,
               last_seen_at  TEXT,
               last_seen_ip  TEXT,
               samples_total DOUBLE NOT NULL DEFAULT 0,
               rejected_total DOUBLE NOT NULL DEFAULT 0
           );

CREATE INDEX IF NOT EXISTS idx_devices_tenant ON ingest_devices (tenant_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_token ON ingest_devices (token_hash);



-- ======================================================================
-- store: scenes — Cached 3-D scene payloads
-- ======================================================================

CREATE TABLE IF NOT EXISTS scene_cache (
               tenant_id   VARCHAR(255) PRIMARY KEY,
               scene       JSON NOT NULL,
               updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
           );



-- ======================================================================
-- store: bundles — Published agent bundles
-- ======================================================================

CREATE TABLE IF NOT EXISTS published_bundles (
               bundle_id   VARCHAR(255) PRIMARY KEY,
               name        TEXT NOT NULL,
               domains     JSON NOT NULL,
               payload     JSON NOT NULL,
               tenant_id   TEXT,
               created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
           );



-- ======================================================================
-- store: threed — Photo-to-3-D job records
-- ======================================================================

CREATE TABLE IF NOT EXISTS threed_jobs (
               job_id    VARCHAR(255) PRIMARY KEY,
               status    TEXT NOT NULL,
               stage     TEXT,
               filename  TEXT,
               fields    JSON,
               stages    JSON,
               state     JSON,
               error     TEXT,
               created   DOUBLE NOT NULL,
               updated   DOUBLE NOT NULL
           );

CREATE INDEX IF NOT EXISTS idx_threed_updated ON threed_jobs (updated DESC);



-- ======================================================================
-- store: checkpoints — Agent run checkpoints
-- ======================================================================

CREATE TABLE IF NOT EXISTS checkpoints (
               thread_id   VARCHAR(255) PRIMARY KEY,
               graph_name  TEXT NOT NULL,
               state       JSON NOT NULL,
               resume_at   TEXT,
               updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
           );



-- ======================================================================
-- store: historian — telemetry measurements
--
-- Declared outside db/schema.py (see historian/schema.py): its key columns
-- need an explicit CHARACTER SET and its timestamps need microsecond
-- precision, neither of which the shared type map expresses.
-- ======================================================================

CREATE TABLE IF NOT EXISTS measurements (
    tenant_id   VARCHAR(191) CHARACTER SET ascii NOT NULL,
    asset_id    VARCHAR(256) CHARACTER SET ascii NOT NULL,
    signal      VARCHAR(512) CHARACTER SET ascii NOT NULL,
    ts          DATETIME(6)  NOT NULL,
    value       DOUBLE,
    unit        VARCHAR(64)  NOT NULL DEFAULT '',
    quality     SMALLINT     NOT NULL DEFAULT 192,
    source      VARCHAR(64)  CHARACTER SET ascii NOT NULL DEFAULT 'api',
    received_at DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, asset_id, signal, ts)
);

CREATE INDEX measurements_tenant_signal_ts ON measurements (tenant_id, signal, ts DESC);


SET FOREIGN_KEY_CHECKS = 1;
