/**
 * AiBadge — says whether an answer came from Claude or from the fallback.
 *
 * Every copilot response carries an `ai` block. The agents are keyless-safe:
 * with no ANTHROPIC_API_KEY they return a deterministic stub rather than
 * failing. That keeps the product up, and it is exactly why this badge is not
 * optional — a stubbed work order reads like a real one, and someone could act
 * on it. Render this next to every agent output.
 */
export function AiBadge({ ai, elapsed }) {
  if (!ai) return null
  const backend = ai.backend || 'stub'

  const look = {
    claude: { cls: 'pill-green', icon: 'ti-sparkles', label: ai.model || 'Claude' },
    stub: { cls: 'pill-amber', icon: 'ti-alert-triangle', label: 'Fallback — not AI' },
    not_applicable: { cls: 'pill-surface', icon: 'ti-circle-check', label: 'Nothing to report' },
  }[backend] || { cls: 'pill-surface', icon: 'ti-help', label: backend }

  const title = backend === 'claude'
    ? [ai.thinking ? 'extended thinking on' : 'no thinking',
       ai.effort ? `effort: ${ai.effort}` : null,
       ai.usage ? `${ai.usage.input}→${ai.usage.output} tokens` : null,
      ].filter(Boolean).join(' · ')
    : (ai.error || '')

  return (
    <span className="ai-badge" title={title}>
      <span className={`pill ${look.cls}`} style={{ fontSize: 10 }}>
        <i className={`ti ${look.icon}`} /> {look.label}
      </span>
      {elapsed != null && <span className="ai-badge-time">{elapsed.toFixed(1)}s</span>}
    </span>
  )
}

/**
 * StubWarning — the explicit "this is not real reasoning" callout.
 * Shown above a result body whenever the fallback produced it, so the warning
 * is impossible to miss even if the badge is scrolled out of view.
 */
export function StubWarning({ ai }) {
  if (!ai || ai.backend !== 'stub') return null
  return (
    <div className="stub-warning">
      <i className="ti ti-alert-triangle" />
      <div>
        <strong>Deterministic fallback — not generated by Claude.</strong>
        <div className="stub-warning-why">{ai.error || 'The agent could not reach the model.'}</div>
      </div>
    </div>
  )
}

export default AiBadge
