/**
 * WorkContext.jsx — the operational identity: which job this account does.
 *
 * `AuthContext` answers "who is signed in, and what data may they touch"
 * (owner/admin/write/read). This answers the other question the dispatch feature
 * needs: WHAT JOB DO THEY DO — supervisor or frontline operator.
 *
 * They are separate on purpose, and the temptation to merge them is worth
 * resisting. A supervisor who may only READ the twin is an ordinary account —
 * they dispatch people, they do not edit the plant model. An operator may well
 * need WRITE, because closing a job writes back. One field could not express
 * both, which is why the server keeps `role` and `persona` as separate columns
 * (see nextxr-ontology/identity/models.py) and why this provider exists next to
 * AuthContext rather than inside it.
 *
 * RENDER FROM `capabilities`, NOT FROM `persona`.
 *
 *     {can('task.assign') && <AssignButton/>}       // yes
 *     {persona === 'supervisor' && <AssignButton/>} // no
 *
 * The capability list is generated by the same table the API refuses with
 * (work/authority.py), so a button drawn this way is a button the server will
 * honour. Branching on the persona name re-implements that table in the browser,
 * and the failure mode is a button that 403s — which reads to the user as a
 * broken product rather than as a permission they do not have.
 */

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import api from '../api/client'
import { useAuthOptional } from './AuthContext'

const WorkContext = createContext(null)

export function WorkProvider({ children }) {
  // Optional, because this provider now also wraps the hub-federated remote,
  // which has no AuthProvider — see useAuthOptional. `auth === null` means "we
  // are inside the hub", which is a different case from "nobody is signed in".
  const auth = useAuthOptional()
  const isSignedIn = Boolean(auth?.isSignedIn)
  const openBackend = Boolean(auth?.openBackend)
  const federated = auth === null
  const [me, setMe] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const reload = useCallback(async () => {
    // No session means no persona to fetch. An open dev backend has no
    // membership either — /work/me answers 403 there, which is correct and not
    // worth a red error box on every page.
    //
    // `federated` is the exception: inside the hub there is no AuthProvider to
    // ask, but the host injects a credential, so the call is worth making and a
    // 403 is handled below like any other.
    if (!isSignedIn && !federated) {
      setMe(null)
      setLoading(false)
      return null
    }
    try {
      const info = await api.work.me()
      setMe(info)
      setError(null)
      return info
    } catch (e) {
      // A 403 here is the ordinary answer for an account with no membership
      // (a platform admin, an API key). Treat it as "no workspace", not as a
      // failure — the panels render their own explanation.
      setMe(null)
      if (e.status !== 403) setError(e)
      return null
    } finally {
      setLoading(false)
    }
  }, [isSignedIn, federated])

  useEffect(() => { reload() }, [reload])

  const value = useMemo(() => {
    const capabilities = me?.capabilities || []
    return {
      me,
      loading,
      error,
      reload,
      persona: me?.persona || null,
      capabilities,
      /** The check every conditional render should use. */
      can: (capability) => capabilities.includes(capability),
      isSupervisor: me?.persona === 'supervisor',
      isOperator: me?.persona === 'frontline',
      // Present so a panel can say "ask your administrator for a role" rather
      // than rendering an empty page that looks broken.
      hasWorkspace: Boolean(me),
      xp: me?.xp || null,
      openBackend,
      signedIn: isSignedIn,
    }
  }, [me, loading, error, reload, openBackend, isSignedIn])

  return <WorkContext.Provider value={value}>{children}</WorkContext.Provider>
}

export function useWork() {
  const ctx = useContext(WorkContext)
  if (!ctx) throw new Error('useWork must be used inside <WorkProvider>')
  return ctx
}

export default WorkContext
