"""Emit the platform's relational schema as .sql files, one per dialect.

    python docs/build_sql.py

Writes `docs/sql/schema.mysql.sql` and `docs/sql/schema.sqlite.sql`.

WHY GENERATE RATHER THAN KEEP A HAND-WRITTEN FILE.
`nextxr-ontology/db/schema.py` is the single source of truth: it holds the DDL
with type placeholders (`{id}`, `{str}`, `{json}`, …) and `render()` substitutes
the map for a given backend. A checked-in .sql written by hand is a second
source that drifts the first time somebody adds a column, and drifts silently —
nothing would fail. This script asks the application for its own schema, so the
output is correct by construction or it does not build.

WHY TWO FILES. The same tables are provisioned differently per backend, and the
differences are not cosmetic:

  · `{id}` is VARCHAR(255) on MySQL and TEXT on SQLite, because MySQL cannot
    index bare TEXT and several of these columns are named in CREATE INDEX.
  · `{str}` is VARCHAR(1024) on MySQL, because MySQL forbids a DEFAULT on
    TEXT/BLOB and many of these columns carry one.
  · `{code}` is a short VARCHAR for closed vocabularies (status, severity) that
    are ALSO indexed — at VARCHAR(1024) one such column costs 4096 bytes of key
    and InnoDB's limit for the whole key is 3072.
  · the historian's `measurements` table declares `CHARACTER SET ascii` on its
    key columns for the same index-width reason, and DATETIME(6) for
    microsecond timestamps.

Neither file is a migration. Applying them creates the schema from empty;
`python -m db.migrations` is what moves an existing database forward, and the
`schema_migrations` ledger below is what records where it has got to.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "nextxr-ontology"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from db import schema                      # noqa: E402
from historian import schema as hist        # noqa: E402

OUT = Path(__file__).resolve().parent / "sql"

# Emitted in dependency-of-meaning order: who exists, what they may touch, the
# twins, then everything hung off a twin. There are no foreign keys, so this is
# for the reader rather than for the parser.
STORE_ORDER = [
    ("identity", "Accounts, membership, sessions, API keys, audit"),
    ("twins", "The twin registry"),
    ("work", "Dispatch: teams, tasks, XP, graded runs"),
    ("changelog", "Tamper-evident change log (hash-chained)"),
    ("connectors", "Protocol adapters"),
    ("devices", "Ingest device credentials"),
    ("scenes", "Cached 3-D scene payloads"),
    ("bundles", "Published agent bundles"),
    ("threed", "Photo-to-3-D job records"),
    ("checkpoints", "Agent run checkpoints"),
]

HEADER = """-- NextXR Digital Twin — relational schema ({dialect})
--
-- GENERATED by docs/build_sql.py from nextxr-ontology/db/schema.py.
-- Do not edit by hand: add the column in db/schema.py and re-run, or the two
-- will disagree and nothing will tell you.
--
-- Scope: this is the RECORD half of the platform. The twin's graph — entities,
-- relationships and findings — lives in Neo4j and is not expressible here; see
-- docs/ER-DIAGRAM.md section 5 for that model and section 1 for why the two are
-- deliberately not joined at the database layer.
--
-- NO FOREIGN KEYS ARE DECLARED, in this file or in the running databases. That
-- is the existing design, not an omission of the generator: referential
-- integrity is enforced in the service layer (work/service.py,
-- identity/service.py) and supported by the indexes below. Adding constraints
-- here would describe guarantees the system does not actually make.
--
-- This is not a migration. It creates the schema from empty; use
-- `python -m db.migrations` to move an existing database forward.
--
-- {backend_note}
{charset}
"""

MYSQL_NOTE = ("Target: MySQL 8 (RDS in production). One database holds every "
              "store, so a\n-- login and the twin it authorises share a "
              "transaction domain.")
SQLITE_NOTE = ("Target: SQLite (local development). Each store is its own file "
               "under\n-- nextxr-ontology/data/, so cross-store statements are "
               "not possible there.")

MYSQL_PREAMBLE = """
-- Recommended session settings for applying this file.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- CREATE DATABASE IF NOT EXISTS nextxr
--   CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
-- USE nextxr;
"""

SQLITE_PREAMBLE = """
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = OFF;   -- none are declared; stated so the reader knows
"""

# The migration ledger. It is created by db/migrations.py rather than by
# schema.py, so render() does not know about it — but a schema dump without it
# would produce a database that `python -m db.migrations` then thinks is
# unmigrated and tries to re-apply from 0001.
LEDGER = {
    "mysql": """CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_id VARCHAR(255) NOT NULL PRIMARY KEY,
    applied_at   DATETIME     NOT NULL,
    duration_ms  INT          NOT NULL DEFAULT 0,
    checksum     VARCHAR(255) NOT NULL DEFAULT ''
);""",
    "sqlite": """CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_id TEXT    NOT NULL PRIMARY KEY,
    applied_at   TEXT    NOT NULL,
    duration_ms  INTEGER NOT NULL DEFAULT 0,
    checksum     TEXT    NOT NULL DEFAULT ''
);""",
}


def _clean(stmt: str) -> str:
    """One statement, tidied and terminated."""
    lines = [ln.rstrip() for ln in stmt.strip().splitlines()]
    return "\n".join(lines) + ";"


def build(dialect: str) -> str:
    is_my = dialect == "mysql"
    parts = [HEADER.format(
        dialect="MySQL 8" if is_my else "SQLite 3",
        backend_note=MYSQL_NOTE if is_my else SQLITE_NOTE,
        charset=MYSQL_PREAMBLE if is_my else SQLITE_PREAMBLE)]

    parts.append("\n-- ===================================================="
                 "==================\n-- Migration ledger\n"
                 "-- ===================================================="
                 "==================\n")
    parts.append(LEDGER[dialect])

    for store, blurb in STORE_ORDER:
        parts.append(f"\n\n-- ================================================"
                     f"======================\n-- store: {store} — {blurb}\n"
                     f"-- ================================================"
                     f"======================\n")
        for stmt in schema.render(store, dialect):
            parts.append(_clean(stmt))
            parts.append("")

    parts.append("\n\n-- ===================================================="
                 "==================\n-- store: historian — telemetry "
                 "measurements\n--\n-- Declared outside db/schema.py (see "
                 "historian/schema.py): its key columns\n-- need an explicit "
                 "CHARACTER SET and its timestamps need microsecond\n"
                 "-- precision, neither of which the shared type map "
                 "expresses.\n-- ==============================================="
                 "=======================\n")
    if is_my:
        parts.append(_clean(hist._MYSQL_CREATE_RAW))
        parts.append("")
        parts.append(_clean(hist._MYSQL_IDX_SIGNAL))
    else:
        parts.append(_clean(hist._SQLITE_CREATE_RAW))
        parts.append("")
        parts.append(_clean(
            f"CREATE INDEX IF NOT EXISTS {hist.RAW_TABLE}_tenant_signal_ts "
            f"ON {hist.RAW_TABLE} (tenant_id, signal, ts DESC)"))

    if is_my:
        parts.append("\n\nSET FOREIGN_KEY_CHECKS = 1;")
    return "\n".join(parts) + "\n"


def main() -> int:
    OUT.mkdir(exist_ok=True)
    for dialect in ("mysql", "sqlite"):
        text = build(dialect)
        path = OUT / f"schema.{dialect}.sql"
        path.write_text(text, encoding="utf-8")
        tables = text.count("CREATE TABLE")
        indexes = text.count("CREATE INDEX") + text.count("CREATE UNIQUE INDEX")
        print(f"{path.relative_to(OUT.parent.parent)}  "
              f"{len(text)//1024} KB · {tables} tables · {indexes} indexes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
